import appJSON from '../../../package.json'

export const FETCH_COMMENTS_REQUEST = `${appJSON.name}/COMMENTS/FETCH_COMMENTS_REQUEST`
export const FETCH_COMMENTS_SUCCESS = `${appJSON.name}/COMMENTS/FETCH_COMMENTS_SUCCESS`
export const FETCH_COMMENTS_ERROR = `${appJSON.name}/COMMENTS/FETCH_COMMENTS_ERROR`

export const CREATE_NEW_COMMENT = `${appJSON.name}/COMMENTS/CREATE_NEW_COMMENT`
export const REINIT_DATA_COMMENTS = `${appJSON.name}/COMMENTS/REINIT_DATA_COMMENTS`
